<?php 
 $fis_data=
Array
(
"tplData" => array
(
"curCity" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
"isOpen" => "1",
"insertUser" => "liukang317@emao.com",
"userId" => "90",
"addTime" => "1433153262",
),
"ad" => array
(
"2" => array
(
"id" => "2",
"adName" => "rrrrrrrrrrr1",
"pic" => "http://img.emao.net/mall/material/nd/bak/ndan.jpg",
"linkUrl" => "",
"createTime" => "1433212006",
"updateTime" => "",
"insertUser" => "liukang317@emao.com",
"sort" => "4",
"bgcolor" => "131925",
"mpic" => "http://img.emao.net/mall/material/nd/bak/hklr.jpg",
"mlinkUrl" => "http://www.baidu.com",
),
"4" => array
(
"id" => "4",
"adName" => "11",
"pic" => "http://img.emao.net/mall/material/nd/bak/laos.jpg",
"linkUrl" => "",
"createTime" => "1433212033",
"updateTime" => "",
"insertUser" => "liukang317@emao.com",
"sort" => "3",
"bgcolor" => "0c1b12",
"mpic" => "http://img.emao.net/mall/material/nd/bal/lbxe.jpg",
"mlinkUrl" => "http://www.qq.com",
),
"3" => array
(
"id" => "3",
"adName" => "fasdfsa1",
"pic" => "http://img.emao.net/mall/material/nd/bak/frdi.jpg",
"linkUrl" => "http://abc.com",
"createTime" => "1433211879",
"updateTime" => "",
"insertUser" => "liukang317@emao.com",
"sort" => "2",
"bgcolor" => "fffff2",
"mpic" => "http://img.emao.net/mall/material/nd/bal/myjn.jpg",
"mlinkUrl" => "http://abc.com",
),
"5" => array
(
"id" => "5",
"adName" => "温柔1",
"pic" => "http://img.emao.net/mall/material/nd/bak/lamw.jpg",
"linkUrl" => "",
"createTime" => "1433212165",
"updateTime" => "",
"insertUser" => "liukang317@emao.com",
"sort" => "1",
"bgcolor" => "fffff2",
"mpic" => "http://img.emao.net/mall/material/nd/bal/ibdc.jpg",
"mlinkUrl" => "http://www.sina.com",
),
),
"recBrand" => array
(
"1" => array
(
"id" => "1",
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"website" => "http://www.astonmartin-china.com",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => " 阿斯顿·马丁（AstonMartin）公司设在英国盖顿，生产敞篷旅行车、赛车和限量生产的跑车。建于1913年，创始人是莱昂内尔·马丁和罗伯特·班。1987年被美国福特公司收购。2007年，Prodrive老板大卫·理查兹以9.25亿美元的价格从福特手中购得阿斯顿·马丁。",
"companyName" => "阿斯顿·马丁",
"foreignName" => "Aston Martin",
"address" => "英国盖顿",
"foundDate" => "0000-00-00",
"meaning" => "阿斯顿·马丁汽车标志为一只展翅飞翔的大鹏，喻示该公司像大鹏鸟一样，具有从天而降的冲刺速度和远大的志向。",
"scope" => "高端赛车、跑车、敞篷旅行车",
"staff" => "0",
"founder" => "莱昂内尔·马丁、罗伯特·班福德",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-15 10:21:55",
"message" => "0",
"source" => "1",
"carscmsId" => "1",
"carscmsCountry" => "英国",
),
"2" => array
(
"id" => "2",
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"website" => "http://www.audi.cn/cn/brand/zh.html",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "奥迪（Audi）是一个国际著名豪华汽车品牌，作为高技术水平、质量标准、创新能力、以及经典车型款式的代表，奥迪是世界最成功的汽车品牌之一。公司总部设在德国的英戈尔施塔特。",
"companyName" => "奥迪汽车公司",
"foreignName" => "Audi",
"address" => "德国 英戈尔施塔特",
"foundDate" => "1910-04-25",
"meaning" => "奥迪轿车的标志为四个圆环，代表着合并前的四家公司。",
"scope" => "高端汽车的生产",
"staff" => "0",
"founder" => "奥古斯特·霍希",
"slogan" => "突破科技，启迪未来。",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:13",
"message" => "0",
"source" => "1",
"carscmsId" => "2",
"carscmsCountry" => "德国",
),
"4" => array
(
"id" => "4",
"brandName" => "宝骏",
"logo" => "http://img.emao.net/car/logo/nd/bah/oikc.png",
"website" => "http://www.autobaojun.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "宝骏是上汽通用五菱2010年创建的自主汽车品牌。上汽通用五菱正式发布的新乘用车品牌“宝骏汽车”，标志这个中国微车领头羊开始正式进军方兴未艾的轿车市场。宝骏品牌源由：“骏”的本义是良驹，宝骏即人们最心爱的良驹。",
"companyName" => "上海通用",
"foreignName" => "shanghaitongyong",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-10 17:18:55",
"message" => "0",
"source" => "1",
"carscmsId" => "4",
"carscmsCountry" => "自主",
),
"5" => array
(
"id" => "5",
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"website" => "http://www.bmw.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "宝马汽车为德系三大豪华品牌之一，宝马的车系有1、2、3、4、5、6、7、i、X、Z等几个系列，还有在各系基础上进行改进的M系（宝马官方的高性能改装部门）。宝马公司创建于1916年，总部设在德国慕尼黑。",
"companyName" => "巴伐利亚机械制造厂股份公司",
"foreignName" => "BayerischeMotorenWerke AG",
"address" => "德国慕尼黑",
"foundDate" => "1916-03-07",
"meaning" => "BMW的蓝白标志象征着蓝天,白云和旋转的螺旋桨。",
"scope" => "高端汽车及摩托车的生产",
"staff" => "0",
"founder" => "吉斯坦·奥托(Gustan Otto)",
"slogan" => "Sheer Driving Pleasure（纯粹驾驶乐趣）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:24",
"message" => "0",
"source" => "1",
"carscmsId" => "5",
"carscmsCountry" => "德国",
),
"6" => array
(
"id" => "6",
"brandName" => "保时捷",
"logo" => "http://img.emao.net/car/logo/nd/bah/kvmy.png",
"website" => "http://www.porsche.com/china/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "保时捷，是德国汽车品牌，1930年由费迪南德·波尔舍教授建于斯图加特。费迪南德·波尔舍是一位享誉世界车坛的著名设计师。保时捷以生产高级跑车而著名于世界车坛。在1932年的巴黎国际展览会上，保时捷已经名扬四海。保时捷汽车具有鲜明的特色，甲壳虫式的车形，后置式发动机和优异的性能，令它很快成为知名的汽车。",
"companyName" => "德国保时捷公司",
"foreignName" => "Porsche",
"address" => "德国斯图加特",
"foundDate" => "1931-04-25",
"meaning" => "通过一幅优美的田园风景画，展现了保时捷公司辉煌的过去，预示了美好的未来及保时捷跑车的出类拔萃。",
"scope" => "高端汽车的开发、生产、营销",
"staff" => "0",
"founder" => "费迪南德·保时捷",
"slogan" => "There Is No Substitute（无可替代）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:32",
"message" => "0",
"source" => "1",
"carscmsId" => "6",
"carscmsCountry" => "德国",
),
"10" => array
(
"id" => "10",
"brandName" => "本田",
"logo" => "http://img.emao.net/car/logo/nd/bah/bmdc.png",
"website" => "http://www.honda.com.cn/",
"firstWord" => "B",
"ssi" => "10",
"csi" => "2",
"classId" => "2",
"intro" => "本田株式会社（本田技研工业株式会社）是世界上最大的摩托车生产厂家，汽车产量和规模也名列世界十大汽车厂家之列。1948年创立，创始人是传奇式人物本田宗一郎。公司总部在东京，雇员总数达18万人左右。现在，本田公司已是一个跨国汽车、摩托车生产销售集团。它的产品除汽车、摩托车外，还有发电机、农机等动力机械产品。",
"companyName" => "本田株式会社",
"foreignName" => "HONDA",
"address" => "日本东京都港区南青山2-1-1",
"foundDate" => "1948-09-09",
"meaning" => "飞跃的本田的技术和本田公司前途无量",
"scope" => "汽车、摩托车",
"staff" => "0",
"founder" => "本田宗一郎",
"slogan" => "让孩子的天空更蔚蓝",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:31:31",
"message" => "0",
"source" => "1",
"carscmsId" => "10",
"carscmsCountry" => "日本",
),
"13" => array
(
"id" => "13",
"brandName" => "别克",
"logo" => "http://img.emao.net/car/logo/nd/bah/gvmt.png",
"website" => "http://www.buick.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "15",
"classId" => "2",
"intro" => "别克（Buick），是由美国通用汽车公司在美国、加拿大和中国创立的一个品牌。它在北美、中国、独联体国家以及中东都有销售。",
"companyName" => "别克汽车公司",
"foreignName" => "BUICK",
"address" => "美国",
"foundDate" => "1904-05-14",
"meaning" => "象征着一种积极进取，不断登攀的精神。",
"scope" => "中高端汽车生产",
"staff" => "0",
"founder" => "大卫 ·邓巴· 别克",
"slogan" => "用心超越，品味无限。",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:33:39",
"message" => "0",
"source" => "1",
"carscmsId" => "13",
"carscmsCountry" => "美国",
),
"9" => array
(
"id" => "9",
"brandName" => "奔腾",
"logo" => "http://img.emao.net/car/logo/nd/bah/iryx.png",
"website" => "http://www.faw-benteng.com/",
"firstWord" => "B",
"ssi" => "1",
"csi" => "1",
"classId" => "1",
"intro" => "奔腾是一汽集团中最“年轻”的品牌之一。作为自主轿车品牌，奔腾依旧采用了高装备、低价格的销售策略，与马自达6共用主要零部件的生产方式也让奔腾品牌轿车主要部件的质量达到了与合资产品相同的水平，从这一点上讲，奔腾产品的核心实力要大于同期的其它自主品牌轿车。",
"companyName" => "一汽轿车",
"foreignName" => "besturn",
"address" => "长春市",
"foundDate" => "2006-08-18",
"meaning" => "品质、性能、科技",
"scope" => "开发、制造、销售乘用车、发动机、变速箱及其配件。",
"staff" => "0",
"founder" => "郭力",
"slogan" => "进取不止",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:41:19",
"message" => "0",
"source" => "1",
"carscmsId" => "9",
"carscmsCountry" => "中国",
),
),
"openBrand" => array
(
"A" => array
(
"0" => array
(
"id" => "1",
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"website" => "http://www.astonmartin-china.com",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => " 阿斯顿·马丁（AstonMartin）公司设在英国盖顿，生产敞篷旅行车、赛车和限量生产的跑车。建于1913年，创始人是莱昂内尔·马丁和罗伯特·班。1987年被美国福特公司收购。2007年，Prodrive老板大卫·理查兹以9.25亿美元的价格从福特手中购得阿斯顿·马丁。",
"companyName" => "阿斯顿·马丁",
"foreignName" => "Aston Martin",
"address" => "英国盖顿",
"foundDate" => "0000-00-00",
"meaning" => "阿斯顿·马丁汽车标志为一只展翅飞翔的大鹏，喻示该公司像大鹏鸟一样，具有从天而降的冲刺速度和远大的志向。",
"scope" => "高端赛车、跑车、敞篷旅行车",
"staff" => "0",
"founder" => "莱昂内尔·马丁、罗伯特·班福德",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-15 10:21:55",
"message" => "0",
"source" => "1",
"carscmsId" => "1",
"carscmsCountry" => "英国",
),
"1" => array
(
"id" => "2",
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"website" => "http://www.audi.cn/cn/brand/zh.html",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "奥迪（Audi）是一个国际著名豪华汽车品牌，作为高技术水平、质量标准、创新能力、以及经典车型款式的代表，奥迪是世界最成功的汽车品牌之一。公司总部设在德国的英戈尔施塔特。",
"companyName" => "奥迪汽车公司",
"foreignName" => "Audi",
"address" => "德国 英戈尔施塔特",
"foundDate" => "1910-04-25",
"meaning" => "奥迪轿车的标志为四个圆环，代表着合并前的四家公司。",
"scope" => "高端汽车的生产",
"staff" => "0",
"founder" => "奥古斯特·霍希",
"slogan" => "突破科技，启迪未来。",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:13",
"message" => "0",
"source" => "1",
"carscmsId" => "2",
"carscmsCountry" => "德国",
),
),
"B" => array
(
"0" => array
(
"id" => "4",
"brandName" => "宝骏",
"logo" => "http://img.emao.net/car/logo/nd/bah/oikc.png",
"website" => "http://www.autobaojun.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "宝骏是上汽通用五菱2010年创建的自主汽车品牌。上汽通用五菱正式发布的新乘用车品牌“宝骏汽车”，标志这个中国微车领头羊开始正式进军方兴未艾的轿车市场。宝骏品牌源由：“骏”的本义是良驹，宝骏即人们最心爱的良驹。",
"companyName" => "上海通用",
"foreignName" => "shanghaitongyong",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-10 17:18:55",
"message" => "0",
"source" => "1",
"carscmsId" => "4",
"carscmsCountry" => "自主",
),
"1" => array
(
"id" => "5",
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"website" => "http://www.bmw.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "宝马汽车为德系三大豪华品牌之一，宝马的车系有1、2、3、4、5、6、7、i、X、Z等几个系列，还有在各系基础上进行改进的M系（宝马官方的高性能改装部门）。宝马公司创建于1916年，总部设在德国慕尼黑。",
"companyName" => "巴伐利亚机械制造厂股份公司",
"foreignName" => "BayerischeMotorenWerke AG",
"address" => "德国慕尼黑",
"foundDate" => "1916-03-07",
"meaning" => "BMW的蓝白标志象征着蓝天,白云和旋转的螺旋桨。",
"scope" => "高端汽车及摩托车的生产",
"staff" => "0",
"founder" => "吉斯坦·奥托(Gustan Otto)",
"slogan" => "Sheer Driving Pleasure（纯粹驾驶乐趣）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:24",
"message" => "0",
"source" => "1",
"carscmsId" => "5",
"carscmsCountry" => "德国",
),
"2" => array
(
"id" => "6",
"brandName" => "保时捷",
"logo" => "http://img.emao.net/car/logo/nd/bah/kvmy.png",
"website" => "http://www.porsche.com/china/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "保时捷，是德国汽车品牌，1930年由费迪南德·波尔舍教授建于斯图加特。费迪南德·波尔舍是一位享誉世界车坛的著名设计师。保时捷以生产高级跑车而著名于世界车坛。在1932年的巴黎国际展览会上，保时捷已经名扬四海。保时捷汽车具有鲜明的特色，甲壳虫式的车形，后置式发动机和优异的性能，令它很快成为知名的汽车。",
"companyName" => "德国保时捷公司",
"foreignName" => "Porsche",
"address" => "德国斯图加特",
"foundDate" => "1931-04-25",
"meaning" => "通过一幅优美的田园风景画，展现了保时捷公司辉煌的过去，预示了美好的未来及保时捷跑车的出类拔萃。",
"scope" => "高端汽车的开发、生产、营销",
"staff" => "0",
"founder" => "费迪南德·保时捷",
"slogan" => "There Is No Substitute（无可替代）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:32",
"message" => "0",
"source" => "1",
"carscmsId" => "6",
"carscmsCountry" => "德国",
),
"3" => array
(
"id" => "10",
"brandName" => "本田",
"logo" => "http://img.emao.net/car/logo/nd/bah/bmdc.png",
"website" => "http://www.honda.com.cn/",
"firstWord" => "B",
"ssi" => "10",
"csi" => "2",
"classId" => "2",
"intro" => "本田株式会社（本田技研工业株式会社）是世界上最大的摩托车生产厂家，汽车产量和规模也名列世界十大汽车厂家之列。1948年创立，创始人是传奇式人物本田宗一郎。公司总部在东京，雇员总数达18万人左右。现在，本田公司已是一个跨国汽车、摩托车生产销售集团。它的产品除汽车、摩托车外，还有发电机、农机等动力机械产品。",
"companyName" => "本田株式会社",
"foreignName" => "HONDA",
"address" => "日本东京都港区南青山2-1-1",
"foundDate" => "1948-09-09",
"meaning" => "飞跃的本田的技术和本田公司前途无量",
"scope" => "汽车、摩托车",
"staff" => "0",
"founder" => "本田宗一郎",
"slogan" => "让孩子的天空更蔚蓝",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:31:31",
"message" => "0",
"source" => "1",
"carscmsId" => "10",
"carscmsCountry" => "日本",
),
"4" => array
(
"id" => "13",
"brandName" => "别克",
"logo" => "http://img.emao.net/car/logo/nd/bah/gvmt.png",
"website" => "http://www.buick.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "15",
"classId" => "2",
"intro" => "别克（Buick），是由美国通用汽车公司在美国、加拿大和中国创立的一个品牌。它在北美、中国、独联体国家以及中东都有销售。",
"companyName" => "别克汽车公司",
"foreignName" => "BUICK",
"address" => "美国",
"foundDate" => "1904-05-14",
"meaning" => "象征着一种积极进取，不断登攀的精神。",
"scope" => "中高端汽车生产",
"staff" => "0",
"founder" => "大卫 ·邓巴· 别克",
"slogan" => "用心超越，品味无限。",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:33:39",
"message" => "0",
"source" => "1",
"carscmsId" => "13",
"carscmsCountry" => "美国",
),
"5" => array
(
"id" => "11",
"brandName" => "比亚迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ilxh.png",
"website" => "http://www.bydauto.com.cn",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "1",
"intro" => "比亚迪股份有限公司创立于1995年，2002年7月31日在香港主板发行上市，公司总部位于中华人民共和国广东省深圳市，是一家拥有IT，汽车和新能源三大产业群的高新技术民营企业。比亚迪在广东、北京、陕西、上海等地共建有九大生产基地，总面积将近700万平方米，并在美国、欧洲、日本、韩国、印度等国和中国台湾、香港地区设有分公司或办事处，现员工总数超过15万人。",
"companyName" => "比亚迪股份有限公司",
"foreignName" => "BYD",
"address" => "中国深圳坪山区比亚迪路3009号",
"foundDate" => "1995-10-28",
"meaning" => "build your dreams（成就梦想）",
"scope" => "IT、汽车、新能源",
"staff" => "0",
"founder" => "王传福",
"slogan" => "平等、务实、激情、创新",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:37:12",
"message" => "0",
"source" => "1",
"carscmsId" => "11",
"carscmsCountry" => "自主",
),
"6" => array
(
"id" => "9",
"brandName" => "奔腾",
"logo" => "http://img.emao.net/car/logo/nd/bah/iryx.png",
"website" => "http://www.faw-benteng.com/",
"firstWord" => "B",
"ssi" => "1",
"csi" => "1",
"classId" => "1",
"intro" => "奔腾是一汽集团中最“年轻”的品牌之一。作为自主轿车品牌，奔腾依旧采用了高装备、低价格的销售策略，与马自达6共用主要零部件的生产方式也让奔腾品牌轿车主要部件的质量达到了与合资产品相同的水平，从这一点上讲，奔腾产品的核心实力要大于同期的其它自主品牌轿车。",
"companyName" => "一汽轿车",
"foreignName" => "besturn",
"address" => "长春市",
"foundDate" => "2006-08-18",
"meaning" => "品质、性能、科技",
"scope" => "开发、制造、销售乘用车、发动机、变速箱及其配件。",
"staff" => "0",
"founder" => "郭力",
"slogan" => "进取不止",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:41:19",
"message" => "0",
"source" => "1",
"carscmsId" => "9",
"carscmsCountry" => "中国",
),
),
"L" => array
(
"0" => array
(
"id" => "61",
"brandName" => "力帆",
"logo" => "http://img.emao.net/car/logo/nd/bah/ncua.png",
"website" => "http://www.lifan.com/",
"firstWord" => "L",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "重庆力帆实业(集团)公司成立于1992年，是中国最大的民营企业之一。历经21年发展，成为以汽车、摩托车的研发、生产、销售（包括出口）为主业，并投资于金融业的大型民营企业。2012年，力帆实业（集团）股份有限公司实现销售收入86.79亿元，产销汽车13.15万辆，出口创汇5.82亿美元，位列重庆民营企业第一位。截至2012年12月，累计申请专利8007件，其中已获授权专利6951件，各项指标居全国同行领先地位。目前，公司现有员工9375余名，其中具有大中专文化程度7080余人。力帆已十度入选中国企业500强，连续多年成为重庆市出口第一名。2010年11月25日，力帆股份在上海证券交易所成功上市，股票代码为601777，是中国首家上市A股的民营乘用车企。",
"companyName" => "重庆力帆实业（集团）公司",
"foreignName" => "lifan",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 19:12:34",
"message" => "0",
"source" => "1",
"carscmsId" => "62",
"carscmsCountry" => "中国",
),
),
),
"selling" => array
(
"0" => array
(
"id" => "1094",
"consumerId" => "23212",
"sellType" => "4",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "13579",
"smsTitle" => "看禁用有配置没",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434696228",
"updateTime" => "1434696272",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434696255",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434696260",
"backTime" => "",
"preSellTime" => "1434695400",
"sellTime" => "1434695400",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436596200",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "看禁用有配置没",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1436625000",
"sellLead" => "看禁用有配置没",
"num" => "10",
"minPrice" => "0.01",
"invoice" => "0",
"goodsType" => "1",
"salestate" => "",
"price" => "10000.00",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "2016-对方水电费水电费",
),
"fullPayOn" => "1",
"isPurchase" => "1",
"sellTimeFormat" => "2015/06/19,14:30:00",
"endSellTimeFormat" => "2015/07/11,14:30:00",
"giftInfo" => array
(
"id" => "1",
"type" => "1",
"cover" => "/mall/nd/baf/ezvc.jpg",
"name" => "啊啊啊aaaaaa",
"price" => "1212.00",
"descr" => "的顶顶顶顶顶顶顶顶顶顶",
"addTime" => "1428058962",
"addUser" => "root",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "987",
"gid" => "1094",
"color" => "7",
"colorName" => "酒红色",
"number" => "10",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "13579",
"autoName" => "对方水电费水电费",
"displacement" => "5614654.0吨",
"gearboxName" => "暂无",
"bodyConstruct" => "水电费水电费",
"driveMode" => "暂无",
"officialOilWear" => "L",
"year" => "2016",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/jzpo.jpg",
"secImg" => array
(
),
),
"1" => array
(
"id" => "1091",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "126",
"autoId" => "955",
"smsTitle" => "看一下详情页面",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434615954",
"updateTime" => "1434618046",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434617681",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434617688",
"backTime" => "",
"preSellTime" => "1434616200",
"sellTime" => "1434616200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436517000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "看一下详情页面",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1436601600",
"sellLead" => "看一下详情页面",
"num" => "50",
"minPrice" => "0.01",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "32.58",
"autoName" => array
(
"brandName" => "奔驰",
"subBrandName" => "北京奔驰",
"serieName" => "奔驰C级",
"autoName" => "2015-C 180 l 运动型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/18,16:30:00",
"endSellTimeFormat" => "2015/07/10,16:30:00",
"giftInfo" => array
(
"id" => "17",
"type" => "1",
"cover" => "/mall/nd/bak/bxna.jpg",
"name" => "500加油卡",
"price" => "500.00",
"descr" => "价值500的加油卡",
"addTime" => "1431485572",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "981",
"gid" => "1091",
"color" => "5",
"colorName" => "北极白",
"number" => "9",
"price" => "0.01",
"sold" => "2",
"isOnSell" => "1",
),
"1" => array
(
"id" => "982",
"gid" => "1091",
"color" => "6",
"colorName" => "锆英石红",
"number" => "10",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"2" => array
(
"id" => "983",
"gid" => "1091",
"color" => "9",
"colorName" => "水晶棕",
"number" => "11",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "984",
"gid" => "1091",
"color" => "18",
"colorName" => "钻石银",
"number" => "10",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"4" => array
(
"id" => "985",
"gid" => "1091",
"color" => "19",
"colorName" => "铱银色",
"number" => "10",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "955",
"autoName" => "C 180 l 运动型",
"displacement" => "1.6T",
"gearboxName" => "7挡手自一体",
"bodyConstruct" => "4门5座三厢车",
"driveMode" => "前置后驱",
"officialOilWear" => "6.1L",
"year" => "2015",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/mtxp.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/jnca.jpg",
"1" => "http://img.emao.net/mall/nd/bal/oegx.jpg",
"2" => "http://img.emao.net/mall/nd/bal/ldmw.jpg",
),
),
"2" => array
(
"id" => "1090",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "5",
"subBrandId" => "7",
"serieId" => "63",
"autoId" => "497",
"smsTitle" => "抵扣券无需上传抵扣券无需上传抵扣券无需上传抵扣券无需上传",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1434615468",
"updateTime" => "1434615507",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434615483",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434615487",
"backTime" => "",
"preSellTime" => "1434614400",
"sellTime" => "1434614400",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436601600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "抵扣券无需上传抵扣券无需上传抵扣券无需上传抵扣券无需上传",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434615300",
"sellLead" => "抵扣券无需上传抵扣券无需上传抵扣券无需上传抵扣券无需上传",
"num" => "2",
"minPrice" => "12.00",
"invoice" => "0",
"goodsType" => "2",
"salestate" => "",
"price" => "48.68",
"autoName" => array
(
"brandName" => "宝马",
"subBrandName" => "华晨宝马",
"serieName" => "宝马3系",
"autoName" => "2015-328Li xDrive豪华设计套装",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/18,16:00:00",
"endSellTimeFormat" => "2015/07/11,16:00:00",
"couponInfo" => array
(
"id" => "63",
"gid" => "1090",
"sellPrice" => "0.01",
"faceValue" => "10000.00",
"couponDesc" => "",
),
"color" => array
(
"0" => array
(
"id" => "974",
"gid" => "1090",
"color" => "1",
"colorName" => "宝石青",
"number" => "1",
"price" => "12.00",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "975",
"gid" => "1090",
"color" => "3",
"colorName" => "哈瓦那灰",
"number" => "1",
"price" => "12.00",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "976",
"gid" => "1090",
"color" => "4",
"colorName" => "冰河银",
"number" => "0",
"price" => "12.00",
"sold" => "1",
"isOnSell" => "1",
),
"3" => array
(
"id" => "977",
"gid" => "1090",
"color" => "5",
"colorName" => "雪山白",
"number" => "0",
"price" => "12.00",
"sold" => "1",
"isOnSell" => "1",
),
"4" => array
(
"id" => "978",
"gid" => "1090",
"color" => "7",
"colorName" => "墨尔本红",
"number" => "0",
"price" => "12.00",
"sold" => "1",
"isOnSell" => "1",
),
"5" => array
(
"id" => "979",
"gid" => "1090",
"color" => "13",
"colorName" => "水晶蓝",
"number" => "0",
"price" => "12.00",
"sold" => "1",
"isOnSell" => "1",
),
"6" => array
(
"id" => "980",
"gid" => "1090",
"color" => "19",
"colorName" => "开士米银",
"number" => "0",
"price" => "12.00",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "497",
"autoName" => "328Li xDrive豪华设计套装",
"displacement" => "2.0T",
"gearboxName" => "8挡手自一体",
"bodyConstruct" => "4门5座三厢车",
"driveMode" => "前置四驱",
"officialOilWear" => "-L",
"year" => "2015",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/gskb.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/nyfu.jpg",
"1" => "http://img.emao.net/mall/nd/bal/edtf.jpg",
"2" => "http://img.emao.net/mall/nd/bal/iiuu.jpg",
),
),
"3" => array
(
"id" => "1088",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "12",
"autoId" => "137",
"smsTitle" => "整车必须上传整车必须上传整车必须上传整车必须上传整车必须上传",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1434596369",
"updateTime" => "1434596404",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434596385",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434596389",
"backTime" => "",
"preSellTime" => "1434594600",
"sellTime" => "1434594600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436581800",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "整车必须上传整车必须上传整车必须上传整车必须上传",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434596100",
"sellLead" => "整车必须上传整车必须上传整车必须上传整车必须上传整车必须上传",
"num" => "8",
"minPrice" => "0.01",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "19.99",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A3",
"autoName" => "2014-Sportback 35TFSI自动 进取型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/18,10:30:00",
"endSellTimeFormat" => "2015/07/11,10:30:00",
"giftInfo" => array
(
"id" => "19",
"type" => "1",
"cover" => "/mall/nd/bak/hsyn.jpg",
"name" => "100元超市卡",
"price" => "100.00",
"descr" => "100元超市卡",
"addTime" => "1431486338",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "955",
"gid" => "1088",
"color" => "1",
"colorName" => "幻影黑",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"1" => array
(
"id" => "956",
"gid" => "1088",
"color" => "3",
"colorName" => "季风灰",
"number" => "0",
"price" => "0.02",
"sold" => "1",
"isOnSell" => "1",
),
"2" => array
(
"id" => "957",
"gid" => "1088",
"color" => "4",
"colorName" => "莲花灰",
"number" => "1",
"price" => "0.03",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "958",
"gid" => "1088",
"color" => "5",
"colorName" => "冰川白",
"number" => "1",
"price" => "0.04",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "959",
"gid" => "1088",
"color" => "6",
"colorName" => "炫目红",
"number" => "1",
"price" => "0.05",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "960",
"gid" => "1088",
"color" => "7",
"colorName" => "米萨诺红",
"number" => "0",
"price" => "0.05",
"sold" => "1",
"isOnSell" => "1",
),
"6" => array
(
"id" => "961",
"gid" => "1088",
"color" => "8",
"colorName" => "萨摩亚",
"number" => "1",
"price" => "0.04",
"sold" => "0",
"isOnSell" => "1",
),
"7" => array
(
"id" => "962",
"gid" => "1088",
"color" => "9",
"colorName" => "斯科巴",
"number" => "1",
"price" => "0.03",
"sold" => "0",
"isOnSell" => "1",
),
"8" => array
(
"id" => "963",
"gid" => "1088",
"color" => "10",
"colorName" => "白鲸棕",
"number" => "1",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"9" => array
(
"id" => "964",
"gid" => "1088",
"color" => "18",
"colorName" => "希纳兹红",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"10" => array
(
"id" => "965",
"gid" => "1088",
"color" => "19",
"colorName" => "水晶银",
"number" => "1",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"11" => array
(
"id" => "966",
"gid" => "1088",
"color" => "20",
"colorName" => "钛金米",
"number" => "1",
"price" => "0.03",
"sold" => "0",
"isOnSell" => "1",
),
"12" => array
(
"id" => "967",
"gid" => "1088",
"color" => "23",
"colorName" => "阿玛菲",
"number" => "0",
"price" => "0.04",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "137",
"autoName" => "Sportback 35TFSI自动 进取型",
"displacement" => "1.4T",
"gearboxName" => "7挡双离合",
"bodyConstruct" => "5门5座两厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "5.4L",
"year" => "2014",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/gmgd.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/gshq.jpg",
"1" => "http://img.emao.net/mall/nd/bal/evvd.jpg",
"2" => "http://img.emao.net/mall/nd/bal/hwpc.jpg",
),
),
"4" => array
(
"id" => "1087",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "5",
"subBrandId" => "7",
"serieId" => "63",
"autoId" => "497",
"smsTitle" => "12",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1434537687",
"updateTime" => "1434537728",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434537710",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434537714",
"backTime" => "",
"preSellTime" => "1434537000",
"sellTime" => "1434537000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436610600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "12",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434537540",
"sellLead" => "12",
"num" => "6",
"minPrice" => "0.01",
"invoice" => "0",
"goodsType" => "1",
"salestate" => "",
"price" => "48.68",
"autoName" => array
(
"brandName" => "宝马",
"subBrandName" => "华晨宝马",
"serieName" => "宝马3系",
"autoName" => "2015-328Li xDrive豪华设计套装",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/17,18:30:00",
"endSellTimeFormat" => "2015/07/11,18:30:00",
"giftInfo" => array
(
"id" => "5",
"type" => "1",
"cover" => "/mall/nd/baf/jqtr.jpg",
"name" => "顶顶顶顶顶顶顶顶顶",
"price" => "12.00",
"descr" => "天天天天天天天天天天天天天",
"addTime" => "1428398623",
"addUser" => "root",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "941",
"gid" => "1087",
"color" => "1",
"colorName" => "宝石青",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "942",
"gid" => "1087",
"color" => "3",
"colorName" => "哈瓦那灰",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "943",
"gid" => "1087",
"color" => "4",
"colorName" => "冰河银",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "944",
"gid" => "1087",
"color" => "5",
"colorName" => "雪山白",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "945",
"gid" => "1087",
"color" => "7",
"colorName" => "墨尔本红",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "946",
"gid" => "1087",
"color" => "13",
"colorName" => "水晶蓝",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"6" => array
(
"id" => "947",
"gid" => "1087",
"color" => "19",
"colorName" => "开士米银",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "497",
"autoName" => "328Li xDrive豪华设计套装",
"displacement" => "2.0T",
"gearboxName" => "8挡手自一体",
"bodyConstruct" => "4门5座三厢车",
"driveMode" => "前置四驱",
"officialOilWear" => "-L",
"year" => "2015",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/okmb.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/okmg.jpg",
"1" => "http://img.emao.net/mall/nd/bal/oekt.jpg",
"2" => "http://img.emao.net/mall/nd/bal/nacy.jpg",
),
),
"5" => array
(
"id" => "1085",
"consumerId" => "23212",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434526311",
"updateTime" => "1434526356",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434526332",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434526339",
"backTime" => "",
"preSellTime" => "1434526200",
"sellTime" => "1434526200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436513400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "有默认的赠品整车",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434526140",
"sellLead" => "",
"num" => "5",
"minPrice" => "10000.00",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "368.80",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "2010-6.0L V11",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/17,15:30:00",
"endSellTimeFormat" => "2015/07/10,15:30:00",
"giftInfo" => array
(
"id" => "19",
"type" => "1",
"cover" => "/mall/nd/bak/hsyn.jpg",
"name" => "100元超市卡",
"price" => "100.00",
"descr" => "100元超市卡",
"addTime" => "1431486338",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "935",
"gid" => "1085",
"color" => "1",
"colorName" => "亚光黑",
"number" => "1",
"price" => "10000.00",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "936",
"gid" => "1085",
"color" => "6",
"colorName" => "大红色",
"number" => "1",
"price" => "10000.00",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "937",
"gid" => "1085",
"color" => "11",
"colorName" => "绿色",
"number" => "1",
"price" => "10000.00",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "938",
"gid" => "1085",
"color" => "16",
"colorName" => "紫色",
"number" => "1",
"price" => "10000.00",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "939",
"gid" => "1085",
"color" => "21",
"colorName" => "粉色",
"number" => "1",
"price" => "10000.00",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "1",
"autoName" => "6.0L V11",
"displacement" => "6.0",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "4门4座硬顶跑车",
"driveMode" => "前置后驱",
"officialOilWear" => "工信部未公布L",
"year" => "2010",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/dfrx.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/czqi.jpg",
),
),
"6" => array
(
"id" => "1084",
"consumerId" => "23212",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "2",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434526182",
"updateTime" => "1434526356",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434526334",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434526339",
"backTime" => "",
"preSellTime" => "1434526200",
"sellTime" => "1434526200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436513400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "抵扣券有赠品",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434526080",
"sellLead" => "",
"num" => "11",
"minPrice" => "111.00",
"invoice" => "0",
"goodsType" => "2",
"salestate" => "",
"price" => "358.88",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "2013-6.0L V11",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/17,15:30:00",
"endSellTimeFormat" => "2015/07/10,15:30:00",
"couponInfo" => array
(
"id" => "61",
"gid" => "1084",
"sellPrice" => "1.00",
"faceValue" => "20000.00",
"couponDesc" => "",
),
"color" => array
(
"0" => array
(
"id" => "934",
"gid" => "1084",
"color" => "5",
"colorName" => "白色",
"number" => "11",
"price" => "111.00",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "2",
"autoName" => "6.0L V11",
"displacement" => "6.0L",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "5门4座掀背车",
"driveMode" => "前置后驱",
"officialOilWear" => "-L",
"year" => "2013",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/oknv.jpg",
"secImg" => array
(
),
),
"7" => array
(
"id" => "1078",
"consumerId" => "23212",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "2",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434422509",
"updateTime" => "1434422705",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434422585",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434422608",
"backTime" => "",
"preSellTime" => "1434421800",
"sellTime" => "1434421800",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1435977000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "抵扣券不可退款",
"isRefund" => "0",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1436581800",
"sellLead" => "",
"num" => "93",
"minPrice" => "0.02",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "358.88",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "2013-6.0L V11",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/16,10:30:00",
"endSellTimeFormat" => "2015/07/04,10:30:00",
"couponInfo" => array
(
"id" => "57",
"gid" => "1078",
"sellPrice" => "0.01",
"faceValue" => "0.02",
"couponDesc" => "",
),
"color" => array
(
"0" => array
(
"id" => "910",
"gid" => "1078",
"color" => "5",
"colorName" => "白色",
"number" => "93",
"price" => "0.02",
"sold" => "7",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "2",
"autoName" => "6.0L V11",
"displacement" => "6.0L",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "5门4座掀背车",
"driveMode" => "前置后驱",
"officialOilWear" => "-L",
"year" => "2013",
),
"mainImg" => "",
"secImg" => array
(
),
),
"8" => array
(
"id" => "1077",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434422303",
"updateTime" => "1434422705",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434422589",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434422608",
"backTime" => "",
"preSellTime" => "1434421800",
"sellTime" => "1434421800",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1435977000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "全款绑定赠品",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1436581800",
"sellLead" => "",
"num" => "4",
"minPrice" => "0.01",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "1.8 TFSI 手动舒适型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/16,10:30:00",
"endSellTimeFormat" => "2015/07/04,10:30:00",
"giftInfo" => array
(
"id" => "17",
"type" => "1",
"cover" => "/mall/nd/bak/bxna.jpg",
"name" => "500加油卡",
"price" => "500.00",
"descr" => "价值500的加油卡",
"addTime" => "1431485572",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "904",
"gid" => "1077",
"color" => "11",
"colorName" => "绿色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"1" => array
(
"id" => "905",
"gid" => "1077",
"color" => "12",
"colorName" => "墨绿色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"2" => array
(
"id" => "906",
"gid" => "1077",
"color" => "16",
"colorName" => "紫色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "907",
"gid" => "1077",
"color" => "17",
"colorName" => "橙色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "908",
"gid" => "1077",
"color" => "21",
"colorName" => "粉色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "909",
"gid" => "1077",
"color" => "22",
"colorName" => "浅粉色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "28",
"autoName" => "1.8 TFSI 手动舒适型",
"displacement" => "1.8",
"gearboxName" => "6挡手动",
"bodyConstruct" => "三厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "7.5L",
"year" => "2012",
),
"mainImg" => "",
"secImg" => array
(
),
),
"9" => array
(
"id" => "1022",
"consumerId" => "23212",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1433385139",
"updateTime" => "1434423025",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434363819",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434363973",
"backTime" => "",
"preSellTime" => "1434421800",
"sellTime" => "1434425400",
"underUser" => "liukang317@emao.com",
"underTxt" => "",
"under" => "2",
"endSellTime" => "1436495400",
"endSellCount" => "1",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "测试开售提醒时间",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1435631400",
"sellLead" => "",
"num" => "46",
"minPrice" => "0.02",
"invoice" => "0",
"goodsType" => "2",
"salestate" => "",
"price" => "368.80",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "6.0L V11",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/16,11:30:00",
"endSellTimeFormat" => "2015/07/10,10:30:00",
"couponInfo" => array
(
"id" => "53",
"gid" => "1022",
"sellPrice" => "0.01",
"faceValue" => "0.02",
"couponDesc" => "",
),
"color" => array
(
"0" => array
(
"id" => "707",
"gid" => "1022",
"color" => "1",
"colorName" => "亚光黑",
"number" => "7",
"price" => "0.02",
"sold" => "3",
"isOnSell" => "1",
),
"1" => array
(
"id" => "708",
"gid" => "1022",
"color" => "6",
"colorName" => "大红色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "709",
"gid" => "1022",
"color" => "11",
"colorName" => "绿色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "710",
"gid" => "1022",
"color" => "16",
"colorName" => "紫色",
"number" => "9",
"price" => "0.02",
"sold" => "1",
"isOnSell" => "1",
),
"4" => array
(
"id" => "711",
"gid" => "1022",
"color" => "21",
"colorName" => "粉色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "1",
"autoName" => "6.0L V11",
"displacement" => "6.0",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "4门4座硬顶跑车",
"driveMode" => "前置后驱",
"officialOilWear" => "工信部未公布L",
"year" => "2010",
),
"mainImg" => "",
"secImg" => array
(
),
),
"10" => array
(
"id" => "1054",
"consumerId" => "23217",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434020348",
"updateTime" => "1434364067",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434363671",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434363973",
"backTime" => "",
"preSellTime" => "1434362400",
"sellTime" => "1434364200",
"underUser" => "liukang317@emao.com",
"underTxt" => "",
"under" => "2",
"endSellTime" => "1435658400",
"endSellCount" => "2",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "1",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1435401000",
"sellLead" => "",
"num" => "4",
"minPrice" => "0.01",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "1.8 TFSI 手动舒适型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/15,18:30:00",
"endSellTimeFormat" => "2015/06/30,18:00:00",
"giftInfo" => array
(
"id" => "17",
"type" => "1",
"cover" => "/mall/nd/bak/bxna.jpg",
"name" => "500加油卡",
"price" => "500.00",
"descr" => "价值500的加油卡",
"addTime" => "1431485572",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "818",
"gid" => "1054",
"color" => "11",
"colorName" => "绿色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"1" => array
(
"id" => "819",
"gid" => "1054",
"color" => "12",
"colorName" => "墨绿色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"2" => array
(
"id" => "820",
"gid" => "1054",
"color" => "16",
"colorName" => "紫色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "821",
"gid" => "1054",
"color" => "17",
"colorName" => "橙色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "822",
"gid" => "1054",
"color" => "21",
"colorName" => "粉色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "823",
"gid" => "1054",
"color" => "22",
"colorName" => "浅粉色",
"number" => "1",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "28",
"autoName" => "1.8 TFSI 手动舒适型",
"displacement" => "1.8",
"gearboxName" => "6挡手动",
"bodyConstruct" => "三厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "7.5L",
"year" => "2012",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/eeww.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/kmml.jpg",
"1" => "http://img.emao.net/mall/nd/bal/jcdc.jpg",
),
),
"11" => array
(
"id" => "1049",
"consumerId" => "23217",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "12",
"autoId" => "138",
"smsTitle" => "的酸辣粉都是的酸辣粉都是的酸辣粉都是",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1433992801",
"updateTime" => "1434364067",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434363767",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434363973",
"backTime" => "",
"preSellTime" => "1434362400",
"sellTime" => "1434364200",
"underUser" => "liukang317@emao.com",
"underTxt" => "",
"under" => "2",
"endSellTime" => "1435658400",
"endSellCount" => "1",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "的酸辣粉都是的酸辣粉都是的酸辣粉都是",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1433992140",
"sellLead" => "的酸辣粉都是的酸辣粉都是的酸辣粉都是的酸辣粉都是",
"num" => "8",
"minPrice" => "0.03",
"invoice" => "0",
"goodsType" => "1",
"salestate" => "",
"price" => "21.89",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A3",
"autoName" => "Sportback 35TFSI自动 时尚型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/15,18:30:00",
"endSellTimeFormat" => "2015/06/30,18:00:00",
"giftInfo" => array
(
"id" => "3",
"type" => "1",
"cover" => "/mall/nd/baf/ebpe.jpg",
"name" => "啊啊啊",
"price" => "12.33",
"descr" => "顶顶顶顶顶顶顶顶顶顶",
"addTime" => "1428059279",
"addUser" => "root",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "798",
"gid" => "1049",
"color" => "3",
"colorName" => "季风灰",
"number" => "1",
"price" => "230000.00",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "799",
"gid" => "1049",
"color" => "4",
"colorName" => "莲花灰",
"number" => "0",
"price" => "320000.00",
"sold" => "1",
"isOnSell" => "1",
),
"2" => array
(
"id" => "800",
"gid" => "1049",
"color" => "5",
"colorName" => "冰川白",
"number" => "0",
"price" => "540000.00",
"sold" => "1",
"isOnSell" => "1",
),
"3" => array
(
"id" => "801",
"gid" => "1049",
"color" => "7",
"colorName" => "米萨诺红",
"number" => "1",
"price" => "230000.00",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "802",
"gid" => "1049",
"color" => "10",
"colorName" => "白鲸棕",
"number" => "1",
"price" => "430000.00",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "803",
"gid" => "1049",
"color" => "15",
"colorName" => "海南蓝",
"number" => "1",
"price" => "250000.00",
"sold" => "0",
"isOnSell" => "1",
),
"6" => array
(
"id" => "804",
"gid" => "1049",
"color" => "17",
"colorName" => "萨摩亚",
"number" => "1",
"price" => "250000.00",
"sold" => "0",
"isOnSell" => "1",
),
"7" => array
(
"id" => "805",
"gid" => "1049",
"color" => "18",
"colorName" => "阿玛菲白色",
"number" => "1",
"price" => "340000.00",
"sold" => "0",
"isOnSell" => "1",
),
"8" => array
(
"id" => "806",
"gid" => "1049",
"color" => "19",
"colorName" => "水晶银",
"number" => "1",
"price" => "32.00",
"sold" => "0",
"isOnSell" => "1",
),
"9" => array
(
"id" => "807",
"gid" => "1049",
"color" => "20",
"colorName" => "钛金米",
"number" => "1",
"price" => "0.03",
"sold" => "0",
"isOnSell" => "1",
),
"10" => array
(
"id" => "808",
"gid" => "1049",
"color" => "23",
"colorName" => "希纳兹",
"number" => "0",
"price" => "0.03",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "138",
"autoName" => "Sportback 35TFSI自动 时尚型",
"displacement" => "1.4T",
"gearboxName" => "7挡双离合",
"bodyConstruct" => "5门5座两厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "5.4L",
"year" => "2014",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/muqm.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/mooo.jpg",
"1" => "http://img.emao.net/mall/nd/bal/fouv.jpg",
"2" => "http://img.emao.net/mall/nd/bal/coax.jpg",
),
),
"12" => array
(
"id" => "1035",
"consumerId" => "23212",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"smsTitle" => "",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1433844001",
"updateTime" => "1434364067",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434363803",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434363973",
"backTime" => "",
"preSellTime" => "1434362400",
"sellTime" => "1434364200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1435658400",
"endSellCount" => "1",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "gq",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1433843640",
"sellLead" => "抵扣券",
"num" => "50",
"minPrice" => "0.02",
"invoice" => "0",
"goodsType" => "2",
"salestate" => "",
"price" => "368.80",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "6.0L V11",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/15,18:30:00",
"endSellTimeFormat" => "2015/06/30,18:00:00",
"couponInfo" => array
(
"id" => "54",
"gid" => "1035",
"sellPrice" => "0.01",
"faceValue" => "0.02",
"couponDesc" => "",
),
"color" => array
(
"0" => array
(
"id" => "742",
"gid" => "1035",
"color" => "1",
"colorName" => "亚光黑",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "743",
"gid" => "1035",
"color" => "6",
"colorName" => "大红色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "744",
"gid" => "1035",
"color" => "11",
"colorName" => "绿色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "745",
"gid" => "1035",
"color" => "16",
"colorName" => "紫色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "746",
"gid" => "1035",
"color" => "21",
"colorName" => "粉色",
"number" => "10",
"price" => "0.02",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "1",
"autoName" => "6.0L V11",
"displacement" => "6.0",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "4门4座硬顶跑车",
"driveMode" => "前置后驱",
"officialOilWear" => "工信部未公布L",
"year" => "2010",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/ntcr.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/dyqa.jpg",
"1" => "http://img.emao.net/mall/nd/bal/bqas.jpg",
"2" => "http://img.emao.net/mall/nd/bal/ektf.jpg",
),
),
"13" => array
(
"id" => "1080",
"consumerId" => "23217",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "s",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1434515100",
"updateTime" => "1434525702",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1434525677",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1434525681",
"backTime" => "",
"preSellTime" => "1434524400",
"sellTime" => "1434524400",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436598000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "88",
"sortState" => "88",
"description" => "s",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1436500800",
"sellLead" => "s",
"num" => "12",
"minPrice" => "240000.00",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "27.30",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "1.8 TFSI 手动舒适型",
),
"fullPayOn" => "0",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/17,15:00:00",
"endSellTimeFormat" => "2015/07/11,15:00:00",
"couponInfo" => array
(
"id" => "58",
"gid" => "1080",
"sellPrice" => "1.00",
"faceValue" => "230000.00",
"couponDesc" => "",
),
"color" => array
(
"0" => array
(
"id" => "912",
"gid" => "1080",
"color" => "11",
"colorName" => "绿色",
"number" => "2",
"price" => "240000.00",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "913",
"gid" => "1080",
"color" => "12",
"colorName" => "墨绿色",
"number" => "2",
"price" => "240000.00",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "914",
"gid" => "1080",
"color" => "16",
"colorName" => "紫色",
"number" => "2",
"price" => "240000.00",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "915",
"gid" => "1080",
"color" => "17",
"colorName" => "橙色",
"number" => "2",
"price" => "240000.00",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "916",
"gid" => "1080",
"color" => "21",
"colorName" => "粉色",
"number" => "2",
"price" => "240000.00",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "917",
"gid" => "1080",
"color" => "22",
"colorName" => "浅粉色",
"number" => "2",
"price" => "240000.00",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "28",
"autoName" => "1.8 TFSI 手动舒适型",
"displacement" => "1.8",
"gearboxName" => "6挡手动",
"bodyConstruct" => "三厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "7.5L",
"year" => "2012",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/ext.jpg",
"secImg" => array
(
),
),
"14" => array
(
"id" => "1089",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "整车无须上传整车无须上传整车无须上传整车无须上传",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1434615246",
"updateTime" => "1434615288",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1434615263",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1434615269",
"backTime" => "",
"preSellTime" => "1434614400",
"sellTime" => "1434614400",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1436601600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "整车无须上传整车无须上传整车无须上传整车无须上传",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434614760",
"sellLead" => "整车无须上传整车无须上传整车无须上传整车无须上传",
"num" => "0",
"minPrice" => "0.01",
"invoice" => "0",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "2012-1.8 TFSI 手动舒适型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/18,16:00:00",
"endSellTimeFormat" => "2015/07/11,16:00:00",
"giftInfo" => array
(
"id" => "19",
"type" => "1",
"cover" => "/mall/nd/bak/hsyn.jpg",
"name" => "100元超市卡",
"price" => "100.00",
"descr" => "100元超市卡",
"addTime" => "1431486338",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "968",
"gid" => "1089",
"color" => "11",
"colorName" => "绿色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"1" => array
(
"id" => "969",
"gid" => "1089",
"color" => "12",
"colorName" => "墨绿色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"2" => array
(
"id" => "970",
"gid" => "1089",
"color" => "16",
"colorName" => "紫色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"3" => array
(
"id" => "971",
"gid" => "1089",
"color" => "17",
"colorName" => "橙色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"4" => array
(
"id" => "972",
"gid" => "1089",
"color" => "21",
"colorName" => "粉色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
"5" => array
(
"id" => "973",
"gid" => "1089",
"color" => "22",
"colorName" => "浅粉色",
"number" => "0",
"price" => "0.01",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "28",
"autoName" => "1.8 TFSI 手动舒适型",
"displacement" => "1.8",
"gearboxName" => "6挡手动",
"bodyConstruct" => "三厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "7.5L",
"year" => "2012",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/mnvl.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bal/czki.jpg",
"1" => "http://img.emao.net/mall/nd/bal/bizr.jpg",
"2" => "http://img.emao.net/mall/nd/bal/lppi.jpg",
),
),
),
"willSell" => array
(
"0" => array
(
"id" => "1053",
"consumerId" => "23217",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "21321313321",
"state" => "5",
"insertUser" => "root",
"insertTime" => "1434015476",
"updateTime" => "1434444431",
"submitUser" => "root",
"submitTime" => "1434024486",
"checkUser" => "root",
"checkTime" => "1434024494",
"backTime" => "",
"preSellTime" => "1434443400",
"sellTime" => "1434789000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1435653000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "40",
"sortState" => "40",
"description" => "32133321323",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1434015300",
"sellLead" => "12321321332133",
"num" => "6",
"minPrice" => "110000.00",
"invoice" => "0",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "1.8 TFSI 手动舒适型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"sellTimeFormat" => "2015/06/20,16:30:00",
"endSellTimeFormat" => "2015/06/30,16:30:00",
"giftInfo" => array
(
),
"color" => array
(
"0" => array
(
"id" => "812",
"gid" => "1053",
"color" => "11",
"colorName" => "绿色",
"number" => "1",
"price" => "110000.00",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "813",
"gid" => "1053",
"color" => "12",
"colorName" => "墨绿色",
"number" => "1",
"price" => "110000.00",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "814",
"gid" => "1053",
"color" => "16",
"colorName" => "紫色",
"number" => "1",
"price" => "110000.00",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "815",
"gid" => "1053",
"color" => "17",
"colorName" => "橙色",
"number" => "1",
"price" => "110000.00",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "816",
"gid" => "1053",
"color" => "21",
"colorName" => "粉色",
"number" => "1",
"price" => "110000.00",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "817",
"gid" => "1053",
"color" => "22",
"colorName" => "浅粉色",
"number" => "1",
"price" => "110000.00",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "28",
"autoName" => "1.8 TFSI 手动舒适型",
"displacement" => "1.8",
"gearboxName" => "6挡手动",
"bodyConstruct" => "三厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "7.5L",
"year" => "2012",
),
"mainImg" => "http://img.emao.net/mall/nd/bal/ekin.jpg",
"secImg" => array
(
),
),
),
"pageTitle" => "北京汽车商城_北京特价车_北京网购汽车_一猫商城",
"pageKeyword" => "北京网购汽车,北京买车,北京汽车报价,北京特价车",
"pageDescription" => "北京汽车商城是一猫电商在线买车平台，一猫汽车商城提供北京汽车价格、图片、买车、使用等务信息，北京汽车网报价大全。",
"__loginInfo" => array
(
"id" => "35630",
"username" => "lqx000",
"nickname" => "lqx000",
"realname" => "",
"pwd" => "2a77a3ed9ff4bc69a42ea4fbfbf08ae3",
"birthday" => "",
"sex" => "-1",
"selfintro" => "",
"phone" => "",
"phoneValid" => "",
"mail" => "",
"mailValid" => "",
"nation_id" => "0",
"province_id" => "0",
"city_id" => "0",
"district_id" => "0",
"major" => "",
"mood" => "",
"tags" => "",
"head_img_uri" => "http://s.emao.net/images/common/uc_user_avatar.png",
"role" => "0",
"regIP" => "192.168.20.155",
"login_time" => "2015-06-19 16:58:19",
"reg_time" => "2015-06-02 10:42:48",
"update_time" => "2015-06-19 16:58:19",
"completeStatus" => "5",
"status" => "1",
"source" => "0",
"client" => "1",
"auditStatus" => "0",
"usernameSetted" => "1",
"nicknameSetted" => "0",
"passwordSetted" => "1",
"head_img_url" => "http://s.emao.net/images/common/uc_user_avatar.png",
"avatarSetted" => "0",
"avatar" => "http://s.emao.net/images/common/uc_user_avatar.png",
),
"__serverTime" => "1434705383",
"__serverTimeFormat" => "2015/06/19,17:16:23",
"__openCity" => array
(
"1" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
"isOpen" => "1",
"insertUser" => "liukang317@emao.com",
"userId" => "90",
"addTime" => "1433153262",
),
"3" => array
(
"cityId" => "3",
"cityName" => "石家庄",
"pinyin" => "shijiazhuang",
"isOpen" => "1",
"insertUser" => "root",
"userId" => "1",
"addTime" => "1431416378",
),
),
),
);