<?php 
 $fis_data=
Array
(
"tplData" => array
(
"searchParam" => array
(
"sellType" => "0",
"brandId" => "0",
"carriageId" => "0",
"price" => "3_5",
"carFrom" => "0",
),
"carList" => array
(
"0" => array
(
"id" => "1384",
"consumerId" => "23202",
"sellType" => "4",
"brandId" => "2",
"subBrandId" => "3",
"serieId" => "18",
"autoId" => "232",
"smsTitle" => "整车-普通售卖-非自采 2014-35 FSI quattr",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p>整车-普通售卖-非自采 2014-35 FSI quattro 技术型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p>整车-普通售卖-非自采 2014-35 FSI quattro 技术型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p>整车-普通售卖-非自采 2014-35 FSI quattro 技术型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p>整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p>整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型</p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "root",
"insertTime" => "1439804823",
"updateTime" => "1439804876",
"submitUser" => "root",
"submitTime" => "1439804846",
"checkUser" => "root",
"checkTime" => "1439804857",
"backTime" => "",
"preSellTime" => "1439803800",
"sellTime" => "1439803800",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439890200",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型整车-普通售卖-非自采 2014-35 FSI quattro 技术型",
"isRefund" => "0",
"discountWay" => "1",
"discount" => "10",
"contractNo" => "gtest123",
"finalTime" => "1439890200",
"sellLead" => "整车-普通售卖-非自采 2014-35 FSI quattro 技术型",
"num" => "0",
"minPrice" => "0",
"invoice" => "0",
"goodsCat" => "15",
"goodsType" => "1",
"salestate" => "",
"price" => "72.80",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "奥迪(进口)",
"serieName" => "奥迪A7",
"autoName" => "2014-35 FSI quattro 技术型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "整车-普通售卖-非自采 2014-35 FSI quattro 技术型",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "2",
"tpl" => "1",
"multiple" => "0",
"sellTimeFormat" => "2015/08/17,17:30:00",
"endSellTimeFormat" => "2015/08/18,17:30:00",
"mainImg" => "http://img.emao.net/mall/nd/bai/jmqz.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/hqew.jpg",
),
),
"1" => array
(
"id" => "1382",
"consumerId" => "23202",
"sellType" => "4",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "52",
"smsTitle" => "新的方法写的商品名称-2015-30 TFSI 手动舒适型",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p>新的方法写的商品名称-2015-30 TFSI 手动舒适型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p>新的方法写的商品名称-2015-30 TFSI 手动舒适型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p>新的方法写的商品名称-2015-30 TFSI 手动舒适型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p>新的方法写的商品名称-2015-30 TFSI 手动舒适型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p>新的方法写的商品名称-2015-30 TFSI 手动舒适型</p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "root",
"insertTime" => "1439802558",
"updateTime" => "1439803191",
"submitUser" => "root",
"submitTime" => "1439803021",
"checkUser" => "root",
"checkTime" => "1439803146",
"backTime" => "",
"preSellTime" => "1439802000",
"sellTime" => "1439802000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1440147600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "新的方法写的商品名称-2015-30 TFSI 手动舒适型新的方法写的商品名称-2015-30 TFSI 手动舒适型新的方法写的商品名称-2015-30 TFSI 手动舒适型",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "tcm20150817-001",
"finalTime" => "1439802240",
"sellLead" => "新的方法写的商品名称-2015-30 TFSI 手动舒适型",
"num" => "30",
"minPrice" => "0.01",
"invoice" => "0",
"goodsCat" => "",
"goodsType" => "1",
"salestate" => "",
"price" => "27.28",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "2015-30 TFSI 手动舒适型",
),
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "0",
"goodsName" => "新的方法写的商品名称-2015-30 TFSI 手动舒适型",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "",
"multiple" => "0",
"sellTimeFormat" => "2015/08/17,17:00:00",
"endSellTimeFormat" => "2015/08/21,17:00:00",
"mainImg" => "http://img.emao.net/mall/nd/bai/gxzr.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/hkdm.jpg",
"1" => "http://img.emao.net/mall/nd/bai/jmrj.jpg",
),
),
"2" => array
(
"id" => "1381",
"consumerId" => "23227",
"sellType" => "2",
"brandId" => "4",
"subBrandId" => "6",
"serieId" => "56",
"autoId" => "401",
"smsTitle" => "不可议",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439802407",
"updateTime" => "1439802447",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439802427",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439802431",
"backTime" => "",
"preSellTime" => "1439802000",
"sellTime" => "1439802000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441443600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "不可议",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "1",
"finalTime" => "1441445400",
"sellLead" => "不可议",
"num" => "110",
"minPrice" => "110000",
"invoice" => "1",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "7.08",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "不可议价的lqx",
"stockType" => "2",
"isTest" => "2",
"bargainType" => "2",
"carriage" => "",
"tpl" => "2",
"multiple" => "4",
"sellTimeFormat" => "2015/08/17,17:00:00",
"endSellTimeFormat" => "2015/09/05,17:00:00",
"couponInfo" => array
(
"id" => "201",
"gid" => "1381",
"sellPrice" => "0.01",
"faceValue" => "10000",
"couponDesc" => "",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/lpek.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/mtlz.jpg",
"1" => "http://img.emao.net/mall/nd/bai/lpee.jpg",
"2" => "http://img.emao.net/mall/nd/bai/heaz.jpg",
),
),
"3" => array
(
"id" => "1339",
"consumerId" => "23226",
"sellType" => "2",
"brandId" => "0",
"subBrandId" => "0",
"serieId" => "0",
"autoId" => "0",
"smsTitle" => "",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439273787",
"updateTime" => "1439455514",
"submitUser" => "root",
"submitTime" => "1439289039",
"checkUser" => "root",
"checkTime" => "1439289047",
"backTime" => "",
"preSellTime" => "1438637400",
"sellTime" => "1439202600",
"underUser" => "root",
"underTxt" => "",
"under" => "2",
"endSellTime" => "1440761400",
"endSellCount" => "1",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "1",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "1",
"finalTime" => "1439273640",
"sellLead" => "1",
"num" => "0",
"minPrice" => "0",
"invoice" => "0",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "99999999",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "1",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "2",
"multiple" => "0",
"sellTimeFormat" => "2015/08/10,18:30:00",
"endSellTimeFormat" => "2015/08/28,19:30:00",
"couponInfo" => array
(
"id" => "177",
"gid" => "1339",
"sellPrice" => "0",
"faceValue" => "0",
"couponDesc" => "",
),
"mainImg" => "",
"secImg" => array
(
),
),
"4" => array
(
"id" => "1361",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "5",
"subBrandId" => "8",
"serieId" => "70",
"autoId" => "658",
"smsTitle" => "yw-抵扣券中规车-2014-50 TFSI quattro",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p>yw-抵扣券中规车-2014-50 TFSI quattro 豪华型</p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "root",
"insertTime" => "1439365419",
"updateTime" => "1439802152",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439802133",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439802138",
"backTime" => "",
"preSellTime" => "1439802000",
"sellTime" => "1439802000",
"underUser" => "root",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441443600",
"endSellCount" => "6",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "1",
"sortState" => "1",
"description" => "yw-抵扣券中规车-2014-50 TFSI quattro 豪华型yw-抵扣券中规车-2014-50 TFSI quattro 豪华型yw-抵扣券中规车-2014-50 TFSI quattro 豪华型yw-抵扣券中规车-2014-50 TFSI quattro 豪华型yw-抵扣券中规车-2014-50 TFSI quattro 豪华型yw-抵扣券中规车-2014-50 TFSI quattro",
"isRefund" => "0",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "dkq-20150812-001",
"finalTime" => "1439393400",
"sellLead" => "yw-抵扣券中规车-2014-50 TFSI quattro 豪华型yw-抵扣券中规车-2014-5",
"num" => "67",
"minPrice" => "0",
"invoice" => "0",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "93.35",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "不可议价-yw-抵扣券中规车-2014-50 TFSI quattro 豪华型",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "2",
"multiple" => "34",
"sellTimeFormat" => "2015/08/17,17:00:00",
"endSellTimeFormat" => "2015/09/05,17:00:00",
"couponInfo" => array
(
"id" => "190",
"gid" => "1361",
"sellPrice" => "0.01",
"faceValue" => "10",
"couponDesc" => "价值10元的抵扣券,只需要1分钱就可以购买哦,实惠多多",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/gful.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/opxs.jpg",
"1" => "http://img.emao.net/mall/nd/bai/mzmz.jpg",
"2" => "http://img.emao.net/mall/nd/bai/jyri.jpg",
),
),
"5" => array
(
"id" => "1377",
"consumerId" => "23227",
"sellType" => "2",
"brandId" => "4",
"subBrandId" => "6",
"serieId" => "58",
"autoId" => "422",
"smsTitle" => "1",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439456602",
"updateTime" => "1439456642",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439456620",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439456625",
"backTime" => "",
"preSellTime" => "1439456400",
"sellTime" => "1439456400",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441443600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "1",
"sortState" => "1",
"description" => "1",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "1",
"finalTime" => "1441443600",
"sellLead" => "1",
"num" => "66",
"minPrice" => "0",
"invoice" => "1",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "6.58",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "1",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "2",
"multiple" => "3",
"sellTimeFormat" => "2015/08/13,17:00:00",
"endSellTimeFormat" => "2015/09/05,17:00:00",
"couponInfo" => array
(
"id" => "198",
"gid" => "1377",
"sellPrice" => "10000",
"faceValue" => "220000",
"couponDesc" => "",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/drfi.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/ljed.jpg",
"1" => "http://img.emao.net/mall/nd/bai/jgqe.jpg",
"2" => "http://img.emao.net/mall/nd/bai/owbd.jpg",
),
),
"6" => array
(
"id" => "1363",
"consumerId" => "23227",
"sellType" => "2",
"brandId" => "4",
"subBrandId" => "6",
"serieId" => "57",
"autoId" => "416",
"smsTitle" => "4.68起默认4.98",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439367872",
"updateTime" => "1439367913",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439367893",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439367897",
"backTime" => "",
"preSellTime" => "1439366400",
"sellTime" => "1439366400",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441440000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "1",
"sortState" => "1",
"description" => "d4.68起默认4.98",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "s",
"finalTime" => "1439367660",
"sellLead" => "4.68起默认4.98",
"num" => "60",
"minPrice" => "0",
"invoice" => "0",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "4.68",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "4.68起默认4.98",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "2",
"multiple" => "3",
"sellTimeFormat" => "2015/08/12,16:00:00",
"endSellTimeFormat" => "2015/09/05,16:00:00",
"couponInfo" => array
(
"id" => "192",
"gid" => "1363",
"sellPrice" => "0.01",
"faceValue" => "10000",
"couponDesc" => "",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/gxxa.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/hwdr.jpg",
"1" => "http://img.emao.net/mall/nd/bai/gxxk.jpg",
"2" => "http://img.emao.net/mall/nd/bai/grvx.jpg",
),
),
"7" => array
(
"id" => "1360",
"consumerId" => "23226",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "55",
"smsTitle" => "默认的是4",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439353304",
"updateTime" => "1439361958",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439361933",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439361939",
"backTime" => "",
"preSellTime" => "1439361000",
"sellTime" => "1439361000",
"underUser" => "liqiaoxia381@emao.com",
"underTxt" => "",
"under" => "2",
"endSellTime" => "1441434600",
"endSellCount" => "1",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "1",
"sortState" => "1",
"description" => "默认的是4",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "默认的是4",
"finalTime" => "1440828000",
"sellLead" => "默认的是4",
"num" => "9",
"minPrice" => "10000",
"invoice" => "0",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "默认的是4",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "2",
"carriage" => "",
"tpl" => "2",
"multiple" => "4",
"sellTimeFormat" => "2015/08/12,14:30:00",
"endSellTimeFormat" => "2015/09/05,14:30:00",
"couponInfo" => array
(
"id" => "189",
"gid" => "1360",
"sellPrice" => "0.01",
"faceValue" => "10000",
"couponDesc" => "0.01元抵1元",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/fbmo.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/ichb.jpg",
"1" => "http://img.emao.net/mall/nd/bai/lpea.jpg",
"2" => "http://img.emao.net/mall/nd/bai/kwzl.jpg",
),
),
"8" => array
(
"id" => "1348",
"consumerId" => "23226",
"sellType" => "4",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "7",
"autoId" => "25",
"smsTitle" => "22数量",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439279388",
"updateTime" => "1439279853",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439279829",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439279834",
"backTime" => "",
"preSellTime" => "1439278200",
"sellTime" => "1439278200",
"underUser" => "liqiaoxia381@emao.com",
"underTxt" => "",
"under" => "2",
"endSellTime" => "1441438200",
"endSellCount" => "1",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "11",
"sortState" => "11",
"description" => "22数量",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "1",
"finalTime" => "1439652600",
"sellLead" => "22数量",
"num" => "17",
"minPrice" => "11",
"invoice" => "1",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "526.88",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "1",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "2",
"carriage" => "",
"tpl" => "2",
"multiple" => "2",
"sellTimeFormat" => "2015/08/11,15:30:00",
"endSellTimeFormat" => "2015/09/05,15:30:00",
"couponInfo" => array
(
"id" => "185",
"gid" => "1348",
"sellPrice" => "0.01",
"faceValue" => "20000",
"couponDesc" => "12",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/ftyo.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/eod.jpg",
"1" => "http://img.emao.net/mall/nd/bai/edoe.jpg",
"2" => "http://img.emao.net/mall/nd/bai/evsv.jpg",
),
),
"9" => array
(
"id" => "1347",
"consumerId" => "23230",
"sellType" => "2",
"brandId" => "5",
"subBrandId" => "7",
"serieId" => "63",
"autoId" => "492",
"smsTitle" => "",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439278877",
"updateTime" => "1439279061",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439279036",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439279042",
"backTime" => "",
"preSellTime" => "1439278200",
"sellTime" => "1439278200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1440833400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "11",
"sortState" => "11",
"description" => "10",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "1",
"finalTime" => "1439278800",
"sellLead" => "",
"num" => "10",
"minPrice" => "0",
"invoice" => "1",
"goodsCat" => "27",
"goodsType" => "1",
"salestate" => "",
"price" => "32.80",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "1",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "2",
"multiple" => "1",
"sellTimeFormat" => "2015/08/11,15:30:00",
"endSellTimeFormat" => "2015/08/29,15:30:00",
"couponInfo" => array
(
"id" => "184",
"gid" => "1347",
"sellPrice" => "10000",
"faceValue" => "20000",
"couponDesc" => "",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/jmxl.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/jgvy.jpg",
"1" => "http://img.emao.net/mall/nd/bai/kxgt.jpg",
"2" => "http://img.emao.net/mall/nd/bai/edoa.jpg",
),
),
"10" => array
(
"id" => "1303",
"consumerId" => "23224",
"sellType" => "4",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "12828",
"smsTitle" => "2015-df lqx加的是自采普通售卖不显示库存绿色100",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1439186011",
"updateTime" => "1439189667",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1439189648",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1439189652",
"backTime" => "",
"preSellTime" => "1439188200",
"sellTime" => "1439188200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441434600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "11",
"sortState" => "11",
"description" => "2015-df lqx加的是自采普通售卖不显示库存绿色100辆15万",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "123",
"finalTime" => "1441431000",
"sellLead" => "2015-df lqx加的是自采普通售卖不显示库存绿色100辆15万",
"num" => "100",
"minPrice" => "150000",
"invoice" => "1",
"goodsCat" => "15",
"goodsType" => "1",
"salestate" => "",
"price" => "0",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "df",
),
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "0",
"goodsName" => "2015-df lqx加的是自采普通售卖不显示库存",
"stockType" => "2",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "1",
"multiple" => "0",
"sellTimeFormat" => "2015/08/10,14:30:00",
"endSellTimeFormat" => "2015/09/05,14:30:00",
"mainImg" => "http://img.emao.net/mall/nd/bai/jgrs.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/mzqf.jpg",
"1" => "http://img.emao.net/mall/nd/bai/lvis.jpg",
"2" => "http://img.emao.net/mall/nd/bai/cmzf.jpg",
),
),
"11" => array
(
"id" => "1294",
"consumerId" => "23226",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "12828",
"smsTitle" => "整车中规车允许使用优惠券",
"pcContent" => "<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">推荐理由</div></div><div class=\"detail-con-box\"><p><img alt=\"711014_src.jpg\" src=\"http://img.emao.net/mall/nd/bai/cagz.jpg\" title=\"1438928025797060.jpg\"/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动说明</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">购买须知</div></div><div class=\"detail-con-box\"><p><br/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">车型详情</div></div><div class=\"detail-con-box\"><p><img alt=\"06-免责申明.jpg\" src=\"http://img.emao.net/mall/nd/bai/ihxi.jpg\" title=\"1438928041598111.jpg\"/></p></div><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">免责声明</div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"mContent" => "<div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">推荐理由</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">活动说明</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">购买须知</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">车型详情</div></div><div class=\"detail-nei\"><p><br/></p></div><div class=\"detail-item\" style=\"border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;\"><div class=\"detail-item-nav\" style=\"border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;\">免责声明</div></div><div class=\"detail-nei\"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1438928044",
"updateTime" => "1438928093",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1438928074",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1438928078",
"backTime" => "",
"preSellTime" => "1438927200",
"sellTime" => "1438927200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441432800",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "11",
"sortState" => "11",
"description" => "整车中规车允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "",
"finalTime" => "1441432800",
"sellLead" => "整车中规车允许使用优惠券",
"num" => "9",
"minPrice" => "0.01",
"invoice" => "1",
"goodsCat" => "15",
"goodsType" => "1",
"salestate" => "",
"price" => "0",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "2015-df",
),
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "6",
"goodsName" => "2015-df lqx加的整车",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"carriage" => "",
"tpl" => "1",
"multiple" => "0",
"sellTimeFormat" => "2015/08/07,14:00:00",
"endSellTimeFormat" => "2015/09/05,14:00:00",
"mainImg" => "http://img.emao.net/mall/nd/bai/dqsb.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/cyna.jpg",
"1" => "http://img.emao.net/mall/nd/bai/hdot.jpg",
"2" => "http://img.emao.net/mall/nd/bai/inxw.jpg",
),
),
),
"priceList" => array
(
"1" => "5万以下",
"2" => "5-8万",
"4" => "8-12万",
"8" => "12-18万",
"16" => "18-25万",
"32" => "25-30万",
"64" => "30-50万",
"128" => "50万以上",
),
"carriageList" => array
(
"2" => "两厢",
"4" => "三厢",
"8" => "SUV",
"16" => "MPV",
"256" => "微客",
"2048" => "新能源",
),
"allBrandList" => array
(
"A" => array
(
"0" => array
(
"id" => "1",
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"website" => "http://www.astonmartin-china.com",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => " 阿斯顿·马丁（AstonMartin）公司设在英国盖顿，生产敞篷旅行车、赛车和限量生产的跑车。建于1913年，创始人是莱昂内尔·马丁和罗伯特·班。1987年被美国福特公司收购。2007年，Prodrive老板大卫·理查兹以9.25亿美元的价格从福特手中购得阿斯顿·马丁。",
"companyName" => "阿斯顿·马丁",
"foreignName" => "Aston Martin",
"address" => "英国盖顿",
"foundDate" => "0000-00-00",
"meaning" => "阿斯顿·马丁汽车标志为一只展翅飞翔的大鹏，喻示该公司像大鹏鸟一样，具有从天而降的冲刺速度和远大的志向。",
"scope" => "高端赛车、跑车、敞篷旅行车",
"staff" => "0",
"founder" => "莱昂内尔·马丁、罗伯特·班福德",
"slogan" => "",
"story" => "",
"recommend" => "1",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-07-21 11:05:04",
"message" => "0",
"source" => "1",
"carscmsId" => "1",
"carscmsCountry" => "英国",
),
"1" => array
(
"id" => "2",
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"website" => "http://www.audi.cn/cn/brand/zh.html",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "奥迪（Audi）是一个国际著名豪华汽车品牌，作为高技术水平、质量标准、创新能力、以及经典车型款式的代表，奥迪是世界最成功的汽车品牌之一。公司总部设在德国的英戈尔施塔特。",
"companyName" => "奥迪汽车公司",
"foreignName" => "Audi",
"address" => "德国 英戈尔施塔特",
"foundDate" => "1910-04-25",
"meaning" => "奥迪轿车的标志为四个圆环，代表着合并前的四家公司。",
"scope" => "高端汽车的生产",
"staff" => "0",
"founder" => "奥古斯特·霍希",
"slogan" => "突破科技，启迪未来。",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:13",
"message" => "0",
"source" => "1",
"carscmsId" => "2",
"carscmsCountry" => "德国",
),
),
"B" => array
(
"0" => array
(
"id" => "4",
"brandName" => "宝骏",
"logo" => "http://img.emao.net/car/logo/nd/bah/oikc.png",
"website" => "http://www.autobaojun.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "宝骏是上汽通用五菱2010年创建的自主汽车品牌。上汽通用五菱正式发布的新乘用车品牌“宝骏汽车”，标志这个中国微车领头羊开始正式进军方兴未艾的轿车市场。宝骏品牌源由：“骏”的本义是良驹，宝骏即人们最心爱的良驹。",
"companyName" => "上海通用",
"foreignName" => "shanghaitongyong",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-10 17:18:55",
"message" => "0",
"source" => "1",
"carscmsId" => "4",
"carscmsCountry" => "自主",
),
"1" => array
(
"id" => "3",
"brandName" => "BRABUS巴博斯",
"logo" => "http://img.emao.net/car/logo/nd/bah/lboj.png",
"website" => "http://www.brabuschina.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "BRABUS公司由Bodo Buschmann 先生创建于1977年，现已跻身为全球最大的汽车改装厂商之一。",
"companyName" => "博速公司",
"foreignName" => "BRABUS",
"address" => "鲁尔区",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "汽车改装",
"staff" => "0",
"founder" => "Bodo Buschmann",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-04-15 11:21:48",
"message" => "0",
"source" => "1",
"carscmsId" => "3",
"carscmsCountry" => "德国",
),
"2" => array
(
"id" => "5",
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"website" => "http://www.bmw.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "宝马汽车为德系三大豪华品牌之一，宝马的车系有1、2、3、4、5、6、7、i、X、Z等几个系列，还有在各系基础上进行改进的M系（宝马官方的高性能改装部门）。宝马公司创建于1916年，总部设在德国慕尼黑。",
"companyName" => "巴伐利亚机械制造厂股份公司",
"foreignName" => "BayerischeMotorenWerke AG",
"address" => "德国慕尼黑",
"foundDate" => "1916-03-07",
"meaning" => "BMW的蓝白标志象征着蓝天,白云和旋转的螺旋桨。",
"scope" => "高端汽车及摩托车的生产",
"staff" => "0",
"founder" => "吉斯坦·奥托(Gustan Otto)",
"slogan" => "Sheer Driving Pleasure（纯粹驾驶乐趣）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:24",
"message" => "0",
"source" => "1",
"carscmsId" => "5",
"carscmsCountry" => "德国",
),
"3" => array
(
"id" => "6",
"brandName" => "保时捷",
"logo" => "http://img.emao.net/car/logo/nd/bah/kvmy.png",
"website" => "http://www.porsche.com/china/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "保时捷，是德国汽车品牌，1930年由费迪南德·波尔舍教授建于斯图加特。费迪南德·波尔舍是一位享誉世界车坛的著名设计师。保时捷以生产高级跑车而著名于世界车坛。在1932年的巴黎国际展览会上，保时捷已经名扬四海。保时捷汽车具有鲜明的特色，甲壳虫式的车形，后置式发动机和优异的性能，令它很快成为知名的汽车。",
"companyName" => "德国保时捷公司",
"foreignName" => "Porsche",
"address" => "德国斯图加特",
"foundDate" => "1931-04-25",
"meaning" => "通过一幅优美的田园风景画，展现了保时捷公司辉煌的过去，预示了美好的未来及保时捷跑车的出类拔萃。",
"scope" => "高端汽车的开发、生产、营销",
"staff" => "0",
"founder" => "费迪南德·保时捷",
"slogan" => "There Is No Substitute（无可替代）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:32",
"message" => "0",
"source" => "1",
"carscmsId" => "6",
"carscmsCountry" => "德国",
),
"4" => array
(
"id" => "10",
"brandName" => "本田",
"logo" => "http://img.emao.net/car/logo/nd/bah/bmdc.png",
"website" => "http://www.honda.com.cn/",
"firstWord" => "B",
"ssi" => "10",
"csi" => "2",
"classId" => "2",
"intro" => "本田株式会社（本田技研工业株式会社）是世界上最大的摩托车生产厂家，汽车产量和规模也名列世界十大汽车厂家之列。1948年创立，创始人是传奇式人物本田宗一郎。公司总部在东京，雇员总数达18万人左右。现在，本田公司已是一个跨国汽车、摩托车生产销售集团。它的产品除汽车、摩托车外，还有发电机、农机等动力机械产品。",
"companyName" => "本田株式会社",
"foreignName" => "HONDA",
"address" => "日本东京都港区南青山2-1-1",
"foundDate" => "1948-09-09",
"meaning" => "飞跃的本田的技术和本田公司前途无量",
"scope" => "汽车、摩托车",
"staff" => "0",
"founder" => "本田宗一郎",
"slogan" => "让孩子的天空更蔚蓝",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:31:31",
"message" => "0",
"source" => "1",
"carscmsId" => "10",
"carscmsCountry" => "日本",
),
"5" => array
(
"id" => "13",
"brandName" => "别克",
"logo" => "http://img.emao.net/car/logo/nd/bah/gvmt.png",
"website" => "http://www.buick.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "15",
"classId" => "2",
"intro" => "别克（Buick），是由美国通用汽车公司在美国、加拿大和中国创立的一个品牌。它在北美、中国、独联体国家以及中东都有销售。",
"companyName" => "别克汽车公司",
"foreignName" => "BUICK",
"address" => "美国",
"foundDate" => "1904-05-14",
"meaning" => "象征着一种积极进取，不断登攀的精神。",
"scope" => "中高端汽车生产",
"staff" => "0",
"founder" => "大卫 ·邓巴· 别克",
"slogan" => "用心超越，品味无限。",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-07-23 14:36:16",
"message" => "0",
"source" => "1",
"carscmsId" => "13",
"carscmsCountry" => "美国",
),
"6" => array
(
"id" => "11",
"brandName" => "比亚迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ilxh.png",
"website" => "http://www.bydauto.com.cn",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "1",
"intro" => "比亚迪股份有限公司创立于1995年，2002年7月31日在香港主板发行上市，公司总部位于中华人民共和国广东省深圳市，是一家拥有IT，汽车和新能源三大产业群的高新技术民营企业。比亚迪在广东、北京、陕西、上海等地共建有九大生产基地，总面积将近700万平方米，并在美国、欧洲、日本、韩国、印度等国和中国台湾、香港地区设有分公司或办事处，现员工总数超过15万人。",
"companyName" => "比亚迪股份有限公司",
"foreignName" => "BYD",
"address" => "中国深圳坪山区比亚迪路3009号",
"foundDate" => "1995-10-28",
"meaning" => "build your dreams（成就梦想）",
"scope" => "IT、汽车、新能源",
"staff" => "0",
"founder" => "王传福",
"slogan" => "平等、务实、激情、创新",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:37:12",
"message" => "0",
"source" => "1",
"carscmsId" => "11",
"carscmsCountry" => "自主",
),
"7" => array
(
"id" => "9",
"brandName" => "奔腾",
"logo" => "http://img.emao.net/car/logo/nd/bah/iryx.png",
"website" => "http://www.faw-benteng.com/",
"firstWord" => "B",
"ssi" => "1",
"csi" => "1",
"classId" => "1",
"intro" => "奔腾是一汽集团中最“年轻”的品牌之一。作为自主轿车品牌，奔腾依旧采用了高装备、低价格的销售策略，与马自达6共用主要零部件的生产方式也让奔腾品牌轿车主要部件的质量达到了与合资产品相同的水平，从这一点上讲，奔腾产品的核心实力要大于同期的其它自主品牌轿车。",
"companyName" => "一汽轿车",
"foreignName" => "besturn",
"address" => "长春市",
"foundDate" => "2006-08-18",
"meaning" => "品质、性能、科技",
"scope" => "开发、制造、销售乘用车、发动机、变速箱及其配件。",
"staff" => "0",
"founder" => "郭力",
"slogan" => "进取不止",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:41:19",
"message" => "0",
"source" => "1",
"carscmsId" => "9",
"carscmsCountry" => "中国",
),
),
"L" => array
(
"0" => array
(
"id" => "61",
"brandName" => "力帆",
"logo" => "http://img.emao.net/car/logo/nd/bah/ncua.png",
"website" => "http://www.lifan.com/",
"firstWord" => "L",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "重庆力帆实业(集团)公司成立于1992年，是中国最大的民营企业之一。历经21年发展，成为以汽车、摩托车的研发、生产、销售（包括出口）为主业，并投资于金融业的大型民营企业。2012年，力帆实业（集团）股份有限公司实现销售收入86.79亿元，产销汽车13.15万辆，出口创汇5.82亿美元，位列重庆民营企业第一位。截至2012年12月，累计申请专利8007件，其中已获授权专利6951件，各项指标居全国同行领先地位。目前，公司现有员工9375余名，其中具有大中专文化程度7080余人。力帆已十度入选中国企业500强，连续多年成为重庆市出口第一名。2010年11月25日，力帆股份在上海证券交易所成功上市，股票代码为601777，是中国首家上市A股的民营乘用车企。",
"companyName" => "重庆力帆实业（集团）公司",
"foreignName" => "lifan",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 19:12:34",
"message" => "0",
"source" => "1",
"carscmsId" => "62",
"carscmsCountry" => "中国",
),
),
),
"pageHtml" => "  <span class='p-numList'> <a class='p-num selected' href='javascript:;'>1</a><a href=\"http://temai.emao.com/city/beijing/car-0-0-0-3_5-0-2.html\" >2</a>  </span> <a class=\"p-next\" href=\"http://temai.emao.com/city/beijing/car-0-0-0-3_5-0-2.html\">下一页> </a>",
"__loginInfo" => array
(
),
"__serverTime" => "1439866078",
"__serverTimeFormat" => "2015/08/18,10:47:58",
"__openCity" => array
(
"1" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
"isOpen" => "1",
"insertUser" => "liukang317@emao.com",
"userId" => "90",
"addTime" => "1433153262",
),
"2" => array
(
"cityId" => "2",
"cityName" => "天津",
"pinyin" => "tianjin",
"isOpen" => "1",
"insertUser" => "mall@emao.com",
"userId" => "97",
"addTime" => "1430822126",
),
"3" => array
(
"cityId" => "3",
"cityName" => "石家庄",
"pinyin" => "shijiazhuang",
"isOpen" => "1",
"insertUser" => "root",
"userId" => "1",
"addTime" => "1431416378",
),
"169" => array
(
"cityId" => "169",
"cityName" => "武汉",
"pinyin" => "wuhan",
"isOpen" => "1",
"insertUser" => "root",
"userId" => "1",
"addTime" => "1437037629",
),
),
"curCity" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
),
"__http" => array
(
"temai" => "http://temai.emao.com",
"temai_m" => "http://temai.m.emao.com",
"tejia" => "http://temai.emao.com",
"tejia_m" => "http://temai.m.emao.com",
"i" => "http://i.emao.com",
"i_m" => "http://i.m.emao.com",
),
),
);